### PR TITLE
Remove instructions specific to the libsecp256k1 package.

### PR DESCRIPTION
**Pull request by atoulme**
The package is now pulled through the package manager and compiled by rebar3 automatically via mix.

### CODE REVIEW

**Comment by hayesgm** [comment]
@atoulme Having issues getting this to run, it compiles, but then when I run `mix test`, I get:

```elixir
102) test TransactionTests - ttTransactionTest - TransactionWithSvalueEqual_c_secp256k1n_x05 (Blockchain.TransactionTest)
     test/blockchain/transaction_test.exs:23
     ** (UndefinedFunctionError) function :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available)
```

any thoughts?

**Comment by atoulme** [comment]
Weird, tests pass on CircleCI though. I'll check.

**Comment by atoulme** [comment]
I reproduce locally with a clean checkout locally. I am not sure why CircleCI tests pass. We can close this PR for now, and I'll concentrate on the libsecp256k1 repo directly.

**Comment by hayesgm** [comment]
Yeah, happy to try and figure this out. I'm sure it's a minor configuration issue, probably with how the rebar project is built.

**Pull request closed without merging**
